import { useState, useEffect } from "react";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { X, Plus, Code2, Sparkles } from "lucide-react";

const CATEGORIES = ["Coding", "Writing", "Data Analysis", "Research", "Creative", "Marketing", "Customer Support"];
const AVAILABLE_TOOLS = [
  "File Operations",
  "Web Search",
  "Code Execution",
  "Image Generation",
  "Data Visualization",
  "API Calls",
  "Database Access",
];
const CAPABILITIES = [
  "Natural Language Processing",
  "Code Generation",
  "Data Analysis",
  "Creative Writing",
  "Problem Solving",
  "Research & Summarization",
  "Task Automation",
];

function generateAgentCode(config: {
  name: string;
  systemPrompt: string;
  tools: string[];
  capabilities: string[];
}): string {
  const { name, systemPrompt, tools, capabilities } = config;
  
  const toolsConfig = tools.length > 0 
    ? `  // Available tools: ${tools.join(", ")}`
    : "  // No tools configured";
    
  const capabilitiesComment = capabilities.length > 0
    ? `  // Capabilities: ${capabilities.join(", ")}`
    : "  // No capabilities configured";

  return `/**
 * ${name || "Agent"}
 * Generated by Agentic Marketplace Agent Builder
 */

import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

${capabilitiesComment}
${toolsConfig}

async function runAgent(task: string): Promise<string> {
  const systemPrompt = \`${systemPrompt || "You are a helpful AI assistant."}\`;
  
  try {
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 4096,
      system: systemPrompt,
      messages: [
        {
          role: "user",
          content: task,
        },
      ],
    });

    // Extract text response
    const response = message.content.find(
      (block) => block.type === "text"
    );
    
    return response?.type === "text" ? response.text : "No response";
  } catch (error) {
    console.error("Agent execution error:", error);
    throw error;
  }
}

export default runAgent;
`;
}

export default function AgentBuilder() {
  const { toast } = useToast();

  // Visual Builder State
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState("");
  const [systemPrompt, setSystemPrompt] = useState("");
  const [minPrice, setMinPrice] = useState("");
  const [maxPrice, setMaxPrice] = useState("");
  const [basePrice, setBasePrice] = useState("");
  const [selectedTools, setSelectedTools] = useState<string[]>([]);
  const [selectedCapabilities, setSelectedCapabilities] = useState<string[]>([]);
  const [tags, setTags] = useState<string[]>([]);
  const [currentTag, setCurrentTag] = useState("");

  // Code Editor State
  const [agentCode, setAgentCode] = useState("");
  const [isCodeManuallyEdited, setIsCodeManuallyEdited] = useState(false);

  // Auto-generate code when form changes
  useEffect(() => {
    if (!isCodeManuallyEdited) {
      const generatedCode = generateAgentCode({
        name,
        systemPrompt,
        tools: selectedTools,
        capabilities: selectedCapabilities,
      });
      setAgentCode(generatedCode);
    }
  }, [name, systemPrompt, selectedTools, selectedCapabilities, isCodeManuallyEdited]);

  const createAgentMutation = useMutation({
    mutationFn: async (data: any) => {
      const res = await apiRequest("POST", "/api/dev/agents", data);
      return res.json();
    },
    onSuccess: () => {
      toast({
        title: "Success!",
        description: "Agent created successfully. You can now publish it to the marketplace.",
      });
      // Reset form
      setName("");
      setDescription("");
      setCategory("");
      setSystemPrompt("");
      setMinPrice("");
      setMaxPrice("");
      setBasePrice("");
      setSelectedTools([]);
      setSelectedCapabilities([]);
      setTags([]);
      setIsCodeManuallyEdited(false);
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to create agent",
        variant: "destructive",
      });
    },
  });

  const handleCreateAgent = () => {
    if (!name || !description || !category || !systemPrompt || !minPrice || !maxPrice || !basePrice) {
      toast({
        title: "Missing Fields",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }

    const data = {
      developerId: "demo-developer-1", // In real app, this would come from auth
      name,
      description,
      category,
      systemPrompt,
      minPrice: parseFloat(minPrice),
      maxPrice: parseFloat(maxPrice),
      basePrice: parseFloat(basePrice),
      capabilities: selectedCapabilities,
      toolsEnabled: selectedTools,
      tags,
      agentCode,
    };

    createAgentMutation.mutate(data);
  };

  const toggleTool = (tool: string) => {
    setSelectedTools(prev =>
      prev.includes(tool) ? prev.filter(t => t !== tool) : [...prev, tool]
    );
  };

  const toggleCapability = (cap: string) => {
    setSelectedCapabilities(prev =>
      prev.includes(cap) ? prev.filter(c => c !== cap) : [...prev, cap]
    );
  };

  const addTag = () => {
    if (currentTag && !tags.includes(currentTag)) {
      setTags([...tags, currentTag]);
      setCurrentTag("");
    }
  };

  const removeTag = (tag: string) => {
    setTags(tags.filter(t => t !== tag));
  };

  const handleCodeChange = (newCode: string) => {
    setAgentCode(newCode);
    setIsCodeManuallyEdited(true);
  };

  const handleResetCode = () => {
    setIsCodeManuallyEdited(false);
    const generatedCode = generateAgentCode({
      name,
      systemPrompt,
      tools: selectedTools,
      capabilities: selectedCapabilities,
    });
    setAgentCode(generatedCode);
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="border-b bg-card">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-4xl font-bold mb-2" data-testid="text-page-title">Agent Builder</h1>
              <p className="text-muted-foreground text-lg">Create and deploy AI agents to the marketplace</p>
            </div>
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Sparkles className="h-4 w-4 text-primary" />
              <span>Auto-generating SDK code</span>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left Column - Visual Builder */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-primary" />
                  Visual Builder
                </CardTitle>
                <CardDescription>Configure your agent using the form below</CardDescription>
              </CardHeader>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Basic Information</CardTitle>
                <CardDescription>Configure your agent's identity and description</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Agent Name *</Label>
                  <Input
                    id="name"
                    placeholder="e.g., CodeMaster Pro"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    data-testid="input-name"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="description">Description *</Label>
                  <Textarea
                    id="description"
                    placeholder="Describe what your agent does..."
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    rows={3}
                    data-testid="input-description"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="category">Category *</Label>
                  <Select value={category} onValueChange={setCategory}>
                    <SelectTrigger data-testid="select-category">
                      <SelectValue placeholder="Select category" />
                    </SelectTrigger>
                    <SelectContent>
                      {CATEGORIES.map(cat => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="tags">Tags</Label>
                  <div className="flex gap-2">
                    <Input
                      id="tags"
                      placeholder="Add a tag"
                      value={currentTag}
                      onChange={(e) => setCurrentTag(e.target.value)}
                      onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addTag())}
                      data-testid="input-tag"
                    />
                    <Button onClick={addTag} variant="secondary" size="icon" data-testid="button-add-tag">
                      <Plus className="h-4 w-4" />
                    </Button>
                  </div>
                  {tags.length > 0 && (
                    <div className="flex flex-wrap gap-2 mt-2">
                      {tags.map(tag => (
                        <Badge key={tag} variant="secondary" className="gap-1">
                          {tag}
                          <button onClick={() => removeTag(tag)} className="ml-1">
                            <X className="h-3 w-3" />
                          </button>
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>System Prompt</CardTitle>
                <CardDescription>Define how your agent should behave</CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  placeholder="You are a helpful AI assistant specialized in..."
                  value={systemPrompt}
                  onChange={(e) => setSystemPrompt(e.target.value)}
                  rows={6}
                  data-testid="input-system-prompt"
                />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Pricing & Negotiation</CardTitle>
                <CardDescription>Set your agent's price range for negotiation</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-3 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="minPrice">Minimum Price *</Label>
                    <Input
                      id="minPrice"
                      type="number"
                      step="0.01"
                      placeholder="5.00"
                      value={minPrice}
                      onChange={(e) => setMinPrice(e.target.value)}
                      data-testid="input-min-price"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="basePrice">Base Price *</Label>
                    <Input
                      id="basePrice"
                      type="number"
                      step="0.01"
                      placeholder="10.00"
                      value={basePrice}
                      onChange={(e) => setBasePrice(e.target.value)}
                      data-testid="input-base-price"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="maxPrice">Maximum Price *</Label>
                    <Input
                      id="maxPrice"
                      type="number"
                      step="0.01"
                      placeholder="20.00"
                      value={maxPrice}
                      onChange={(e) => setMaxPrice(e.target.value)}
                      data-testid="input-max-price"
                    />
                  </div>
                </div>
                <p className="text-sm text-muted-foreground">
                  Your agent will negotiate within this range. Base price is the starting offer.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Tools & Capabilities</CardTitle>
                <CardDescription>Select what tools and capabilities your agent has</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-3">
                  <Label>Available Tools</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {AVAILABLE_TOOLS.map(tool => (
                      <Badge
                        key={tool}
                        variant={selectedTools.includes(tool) ? "default" : "outline"}
                        className="cursor-pointer justify-center py-2"
                        onClick={() => toggleTool(tool)}
                        data-testid={`badge-tool-${tool}`}
                      >
                        {tool}
                      </Badge>
                    ))}
                  </div>
                </div>

                <div className="space-y-3">
                  <Label>Capabilities</Label>
                  <div className="grid grid-cols-2 gap-2">
                    {CAPABILITIES.map(cap => (
                      <Badge
                        key={cap}
                        variant={selectedCapabilities.includes(cap) ? "default" : "outline"}
                        className="cursor-pointer justify-center py-2"
                        onClick={() => toggleCapability(cap)}
                        data-testid={`badge-capability-${cap}`}
                      >
                        {cap}
                      </Badge>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Right Column - Generated Code Preview */}
          <div className="space-y-6 lg:sticky lg:top-6 lg:h-fit">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Code2 className="h-5 w-5 text-primary" />
                    Generated Agent Code
                  </div>
                  {isCodeManuallyEdited && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={handleResetCode}
                      data-testid="button-reset-code"
                    >
                      Reset to Auto-Generated
                    </Button>
                  )}
                </CardTitle>
                <CardDescription>
                  {isCodeManuallyEdited 
                    ? "You've manually edited this code. Click 'Reset' to auto-generate again."
                    : "Code auto-generates as you fill the form. You can edit it manually."}
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={agentCode}
                  onChange={(e) => handleCodeChange(e.target.value)}
                  className="font-mono text-sm bg-muted/50"
                  rows={30}
                  data-testid="input-agent-code"
                />
              </CardContent>
            </Card>
          </div>
        </div>

        <div className="flex justify-end gap-4 mt-8 pt-6 border-t">
          <Button variant="outline" size="lg" data-testid="button-cancel">
            Cancel
          </Button>
          <Button 
            size="lg" 
            onClick={handleCreateAgent}
            disabled={createAgentMutation.isPending}
            data-testid="button-create-agent"
          >
            {createAgentMutation.isPending ? "Creating..." : "Create Agent"}
          </Button>
        </div>
      </div>
    </div>
  );
}
